#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Config manager not provided" >&2
  exit 1
fi

CONFIG_MANAGER=$(echo "${1}" | tr '[:upper:]' '[:lower;]')

shift

if [[ "x${CONFIG_MANAGER}" == "x" ]]; then
  echo "No config manager to install" >&2
  exit 1
elif [[ "${CONFIG_MANAGER}" == "puppet" ]]; then
  DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" puppet

  if [ $# -ge 1 ]; then
    installPuppetModules "$@"
  else
    echo "No Puppet modules to install"
  fi
else
  echo "Invalid Config Manager: ${CONFIG_MANAGER}" >&2
  exit 2
fi
