#!/bin/bash

# Find out where current script is executing from and
#   add to path
scriptdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PATH="${scriptdir}:$PATH"

# Find and add functions
functionsdir=$( cd "${scriptdir}/../functions/" && pwd )
for file in $(ls ${functionsdir}); do
  file="${functionsdir}/${file}"
  echo "Including ${file}"
  . "${file}"
done

if [ -z ${ConfigFile} ]; then
  export ConfigFile="github:JungleCatSoftware/CloudConfigs/configs/example@master"
fi

updatePackageManager
upgradePackages

# Download the config file
if ! file=$(download_file "${ConfigFile}"); then
  echo "Error downloading ConfigFile: ${ConfigFile}" >&2
  exit 1
fi

# Source the file
. "${file}"

# Export vars in file
vars=($(grep -E '^[[:alpha:]][[:alnum:]_]*=' "${file}"))
for var in "${vars[@]}"; do
  export $(echo "${var%%=*}")
done

if ! [[ "x${CONFIG_MANAGER}" == "x" ]]; then
  installConfigManager "${CONFIG_MANAGER}"
fi
