#!/bin/bash

# Find out where current script is executing from and
#   add to path
scriptdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export PATH="${scriptdir}:$PATH"

# Find and add functions
functionsdir=$( cd "${scriptdir}/../functions/" && pwd )
for file in $(ls ${functionsdir}); do
  file="${functionsdir}/${file}"
  echo "Including ${file}"
  . "${file}"
done

if [ -z ${ConfigFile} ]; then
  export ConfigFile="github:JungleCatSoftware/CloudConfigs/example/config@master"
fi

updatePackageManager
upgradePackages

# Download the config file
if ! file=$(getfile "${ConfigFile}"); then
  echo "Error downloading ConfigFile: ${ConfigFile}" >&2
  exit 1
fi

# Add export to vars in file
sed -i -E 's/^(export )?([[:alpha:]][[:alnum:]_]*=)/export \2/' "${file}"

# Source the file
. "${file}"

CONFIG_MANAGER=$(echo "${CONFIG_MANAGER}" | tr '[:upper:]' '[:lower:]')

if [[ "x${CONFIG_MANAGER}" == "x" ]]; then
  echo "No config manager to install" >&2
elif [[ "x${CONFIG_MANAGER}" == "xpuppet" ]]; then
  installPuppet

  # Librarian-Puppet config file
  if ! [[ "x${PUPPET_LIBRARIAN_FILE}" == "x" ]]; then
    installLibrarianPuppetModules "${PUPPET_LIBRARIAN_FILE}"
  fi

  # Manually defined modules to download and install
  if [ ${#PUPPET_MODULES[@]} -ge 1 ]; then
    installPuppetModules "${PUPPET_MODULES[@]}"
  fi

  if ! [[ "x${HIERA_FILE}" == "x" ]]; then
    if getHieraFile "${HIERA_FILE}"; then
      getHieraDataFiles "${HIERA_DATA_FILES[@]}"
    fi
  fi
else
  echo "Invalid Config Manager: ${CONFIG_MANAGER}" >&2
fi
